version: '3.9'

services:
  node:
    user: '${USER_ID}:${GROUP_ID}'
    build:
      context: $PWD/docker/node
    command: "npm i:all && npm run start:site:dev"
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:5000
    depends_on:
      - db
    links:
      - database:db

  db:
    restart: unless-stopped
    image: postgres:13-alpine
    ports:
      - 5434:5432
    env_file:
      - $PWD/.env
      - $PWD/.env.local
    volumes:
      - $PWD/.data:/var/lib/postgresql/data
      - $PWD/var:/var/www/var

